theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
title: About-this-dev
repository: coffeestained/about-this-dev
plugins:
  - jekyll-remote-theme
  - jekyll-gzip
baseurl: "/about-this-dev"
url: ""
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json
  - _site
  - src
  - vendor
  - CNAME
  - LICENSE
  - Rakefile
  - old
  - vendor/bundle/
  - index.md.html
  - map.md.html
  - d3.md.html
